export const REQUEST_FEEDBACKS = "REQUEST_FEEDBACKS";
export const RECEIVE_FEEDBACKS = "RECEIVE_FEEDBACKS";

export const REQUEST_CREATE_FEEDBACK = "REQUEST_CREATE_FEEDBACK";
export const RECIEVE_CREATE_FEEDBACK = "RECIEVE_CREATE_FEEDBACK";
