# Generated by Django 3.1 on 2020-09-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20200904_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
